apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity3
  labels:
    app: a1
    zone: z1
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - a1
          topologyKey: zone
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - a1
        topologyKey: kubernetes.io/hostname
  containers:
  - name: with-pod-affinity3
    image: busybox:latest
    command: ['sh', '-c', 'top -b']

