apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deploy
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
        affinity:
          podAffinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: security
                      operator: In
                      values:
                      - S2
                  topologyKey: kubernetes.io/hostname
      containers:
      - name: stress
        image: busybox:latest
        command: ['sh', '-c', 'top -b']

