apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:latest
    command: ['sh', '-c', 'top -b']
    resources:
        requests:
          cpu: "200m"
          memory: "128Mi"
          ephemeral-storage: 100Mi
        limits:
          cpu: "500m"
          memory: "200Mi"
          ephemeral-storage: 200Mi

