
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity5
  namespace: test1
  labels:
    app: a1
    zone: z1
spec:
  containers:
  - name: with-pod-affinity
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'top -b']

