apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: test-deploy1
  namespace: test1
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: hub.c.163.com/public/nginx:1.2.1
            name: nginx
  placement:
    clusters:
    - name: kind1
    - name: kind2
  overrides:
  - clusterName: kind1
    clusterOverrides:
    - path: "/spec/replicas"
      value: 3
    - path: "/spec/template/spec/containers/0/image"
      value: "hub.c.163.com/library/nginx:latest"
    - path: "/metadata/annotations"
      op: "add"
      value:
        foo: bar
    - path: "/metadata/annotations/foo"
      op: "remove"

